inherit_from:
  - .rubocop_fixme.yml

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'docs/**/*'
    - 'tmp/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/javascripts/jasmine_spec.rb'
    - 'spec/tasks/rake_spec.rb'
    - 'spec/views/**/*'

# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

