RSpec/ExpectInHook:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Bundler/OrderedGems:
  Enabled: false
