language: ruby
sudo: false

cache:
  bundler: true

before_install:
  - gem update bundler
  - gem install bundler
  - bundle exec rubocop

rvm:
  - 2.5.8
  - 2.6.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.1.7"
    - "RAILS_VERSION=5.2.3"
