language: ruby
sudo: false
cache: bundler

rvm:
  - 2.5
  - 2.6
  - 2.7

jobs:
  include:
    - name: 'Lint'
      rvm: 2.7
      script: bundle exec rubocop

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.2"
    - "RAILS_VERSION=6.0"
