# theme: documentation-theme-jekyll
# repository: tomjohnson1492/documentation-theme-jekyll

# this property is useful for conditional filtering of content that is separate from the PDF.
output: web

# this appears on the top navigation bar next to the home button
topnav_title: Covid Tracker Central Areas
topnav_tagline: Visualizations for the Regions You Want to Track
topnav_url: https://elrayle.github.io/covid_tracker_central_areas

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: Cortland County, NY Covid Tracker

# this appears as the content title on the homepage for the area
homepage_title: Cortland County, NY and Surround Counties

# this appears at the top of the sidebar
area_title: Cortland County, NY Area
url: https://elrayle.github.io/covid_tracker

# Timezone
tz: America/New_York

# this appears in the footer
company_name: elrayle

# this appears in the footer
organization_link: http://github.com/elrayle/
organization_link_name: github.com/elrayle

# this appears in the footer
#community_link: https://github.com/elrayle
#community_link_name: Community Wiki

# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.
# github_editme_path: tomjohnson1492/documentation-theme-jekyll/blob/gh-pages/

# if you're using disqus for comments, add the shortname here. if not, leave this value blank.
disqus_shortname:

# the preview server used. Leave as is.
host: 127.0.0.1

# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4000

# these are the files and directories that jekyll will exclude from the build
exclude:
  - vendor
  - spec
  - README.md
  - Rakefile
  - update.sh
  - Gemfile*
  - CONTRBUTING.md

feedback_subject_line: Jekyll documentation theme

# used as a contact email for the Feedback link in the top navigation bar
#feedback_email:

# if you uncomment the previous line, the Feedback link gets removed
# feedback_disable: true

# if you uncomment the previous line, it changes the Feedback text
# feedback_text: "Need help?"

# if you uncomment the previous line, it changes where the feedback link points to
# feedback_link: "http://helpy.io/"

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge


# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
collections:
  tooltips:
    output: false

# these are defaults used for the frontmatter for these file types
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: home_sidebar


sidebars:
- home_sidebar

- other

# the description is used in the feed.xml file
description: ""

production_url : https://elrayle.github.io/covid_tracker
BASE_PATH : https://elrayle.github.io/covid_tracker

theme: jekyll-theme-minimal

# needed for sitemap.xml file only
plugins:
  - jekyll-sitemap

github_pages_save_generated_files: ['browse_pages.html']
